//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5420
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Web;
using System.Web.UI;
using System.Text;
using JiraSoap;


namespace WebUI
{
	public partial class Default : System.Web.UI.Page
	{

		public virtual void button1_Clicked (object sender, EventArgs args)
		{
            JSClient js = new JSClient();
			js.init(tbUserName.Text, tbPassword.Text, tbProjectCode.Text);
			
			StringBuilder sb = new StringBuilder();
			
			foreach(RemoteIssueType rit in js.issueTypes)
			{
				sb.AppendLine(rit.name + ": " + rit.id.ToString()); 	
			}
			
			litTypes.Text = sb.ToString();
			
		 	//JSClient.createTestMessage(tbUserName.Text, tbPassword.Text, tbProjectCode.Text);
		}
	}
}

