//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5420
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebUI {
	
	
	public partial class Default {
		
		protected System.Web.UI.HtmlControls.HtmlForm form1;
		
		protected System.Web.UI.WebControls.TextBox tbUserName;
		
		protected System.Web.UI.WebControls.TextBox tbPassword;
		
		protected System.Web.UI.WebControls.TextBox tbProjectCode;
		
		protected System.Web.UI.WebControls.Button button1;
		
		protected System.Web.UI.WebControls.Literal litTypes;
	}
}
